name = "TFC Gamin"
author = "Mason"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a19ae2c9204b914222e9560400a3c2da386c6fd59732f3fc1bb9a7bdd6e94bc0"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
