name = "TFC Gamin"
author = "Mason"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ed07e951d8f3344f13ee4ab48832272ca662a9a6822625c674305250bb3cbfb"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
